name = "rate-my-robot"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

account_id = "d4b834199be0b540ab362c7fe0c3227b"

[[kv_namespaces]]
binding = "GALLERY"
id = "d842874d074f4ae5aa9e4adc1b801805"

[vars]
ENVIRONMENT = "production"
